// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYx9M_16P1Wu7mWZoDVzm4dl54tvDxqTg',
    appId: '1:815176471819:web:a23d63c1da8e8bd8c6fe0e',
    messagingSenderId: '815176471819',
    projectId: 'lab12-it',
    authDomain: 'lab12-it.firebaseapp.com',
    storageBucket: 'lab12-it.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKJL4hmqfvQ_9CreaLWdAckQGYcx-3Fvk',
    appId: '1:815176471819:android:9542f10e9ab02a07c6fe0e',
    messagingSenderId: '815176471819',
    projectId: 'lab12-it',
    storageBucket: 'lab12-it.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHx2R02tJWRsE5ng89b4km8qB_ZMc6mno',
    appId: '1:815176471819:ios:c3b1772981cf7d13c6fe0e',
    messagingSenderId: '815176471819',
    projectId: 'lab12-it',
    storageBucket: 'lab12-it.appspot.com',
    iosClientId: '815176471819-j4jd45im95005qep9is59fpo5qhrp0f2.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHx2R02tJWRsE5ng89b4km8qB_ZMc6mno',
    appId: '1:815176471819:ios:c3b1772981cf7d13c6fe0e',
    messagingSenderId: '815176471819',
    projectId: 'lab12-it',
    storageBucket: 'lab12-it.appspot.com',
    iosClientId: '815176471819-j4jd45im95005qep9is59fpo5qhrp0f2.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab12',
  );
}
